base_model: noeloco/camel-lora
model_type: AutoModelForCausalLM
tokenizer_type: CodeLlamaTokenizer
is_llama_derived_model: true

hub_model_id: noeloco/camel-lora-dpo

load_in_8bit: true
load_in_4bit: false
strict: false

gpu_memory_limit: 20GiB

hf_use_auth_token: true
push_dataset_to_hub: noeloco
val_set_size: 0.05
output_dir: ./lora-out
chat_template: chatml

adapter: lora
lora_model_dir:
lora_r: 8
lora_alpha: 16
lora_dropout: 0.05
lora_target_linear: false
lora_fan_in_fan_out:
lora_target_modules:
  - q_proj
  - v_proj
  - k_proj
  - o_proj
  - gate_proj
  - down_proj
  - up_proj

dpo_beta: 0.7

rl: dpo
datasets:
    - path: noeloco/fizzbuzz-dpo
      split: train
      data_files:
        - /tmp/fizzbuzz-ft/datasets/training-set-dpo.json
      ds_type: json
      type: chatml.intel

sequence_len: 4096
sample_packing: false
pad_to_sequence_len: true

wandb_project: runpod1
wandb_entity:
wandb_watch:
wandb_name: 
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 4
optimizer: paged_adamw_32bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: auto
fp16: false
tf32: true

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
evals_per_epoch: 4
saves_per_epoch: 1
debug: true
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"
